param(
  [string]$RegularTTF = "c:/Users/YULIA/Documents/Arduino/libraries/ST77xx_DMA/src/Fonts/GFXFF/font_mod/RUS/_ttf/times.ttf",
  [string]$BoldTTF    = "c:/Users/YULIA/Documents/Arduino/libraries/ST77xx_DMA/src/Fonts/GFXFF/font_mod/RUS/_ttf/timesbd.ttf",
  [string]$FontconvertExe = "c:/Users/YULIA/Documents/Arduino/libraries/ST77xx_DMA/tools/fonts/fontconvert.exe",
  [int]$MinPx = 5,
  [int]$MaxPx = 40
)

$ErrorActionPreference = 'Stop'

function New-DirectoryIfMissing {
  param([string]$Path)
  if (!(Test-Path -LiteralPath $Path)) { New-Item -ItemType Directory -Path $Path | Out-Null }
}

# Try to resolve fontconvert.exe if not found at the provided path
function Resolve-Fontconvert {
  param([string]$PathCandidate)
  # 1) Provided path
  if ($PathCandidate -and (Test-Path -LiteralPath $PathCandidate)) { return (Resolve-Path $PathCandidate).Path }
  
  # 2) Repo default tools/fonts/fontconvert.exe
  $repoDefault = Join-Path $repoRoot 'tools/fonts/fontconvert.exe'
  if (Test-Path -LiteralPath $repoDefault) { return (Resolve-Path $repoDefault).Path }

  # 3) PATH lookup
  try {
    $cmd = Get-Command fontconvert.exe -ErrorAction Stop
    if ($cmd -and $cmd.Source) { return $cmd.Source }
  } catch {}

  # 4) Arduino libraries (targeted search first)
  $arduinoLibs = Join-Path $env:USERPROFILE 'Documents/Arduino/libraries'
  if (Test-Path -LiteralPath $arduinoLibs) {
    # Common Adafruit GFX layout
    $likely = Get-ChildItem -Path $arduinoLibs -Filter fontconvert.exe -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($likely) { return $likely.FullName }
  }

  # 5) Downloads quick check
  $dl = Join-Path $env:USERPROFILE 'Downloads/fontconvert.exe'
  if (Test-Path -LiteralPath $dl) { return (Resolve-Path $dl).Path }

  throw "fontconvert.exe not found. Укажите путь параметром -FontconvertExe или поместите в tools/fonts/."
}

# Paths
$repoRoot = Split-Path -Parent (Split-Path -Parent $PSCommandPath) # tools/fonts -> tools -> repo
$rusRoot  = Join-Path $repoRoot 'src/Fonts/GFXFF/font_mod/RUS'
$outRoot  = Join-Path $rusRoot 'generated'
$regDir   = Join-Path $outRoot 'regular'
$bdDir    = Join-Path $outRoot 'bold'

New-DirectoryIfMissing $outRoot
New-DirectoryIfMissing $regDir
New-DirectoryIfMissing $bdDir

# Checks
if (!(Test-Path -LiteralPath $RegularTTF)) { throw "Regular TTF not found: $RegularTTF" }
if (!(Test-Path -LiteralPath $BoldTTF)) { throw "Bold TTF not found: $BoldTTF" }
$FontconvertExe = Resolve-Fontconvert -PathCandidate $FontconvertExe
Write-Host "Using fontconvert: $FontconvertExe"

# Cyrillic basic block U+0400..U+045F (1024..1119). NOTE: U+2116 (№) is not in this block.
$cpFirst = 1024
$cpLast  = 1119

# Generate headers
$pxList = $MinPx..$MaxPx
Write-Host "Regular TTF: $RegularTTF"
Write-Host "Bold    TTF: $BoldTTF"
Write-Host "Sizes: $MinPx..$MaxPx, Codepoints: $cpFirst..$cpLast"

foreach ($px in $pxList) {
  $regOut = Join-Path $regDir ("tnr_ru_{0}pt7b.h" -f $px)
  $bdOut  = Join-Path $bdDir  ("tnr_rubd_{0}pt7b.h" -f $px)

  # Regular
  try {
    $out = & $FontconvertExe $RegularTTF $px $cpFirst $cpLast 2>&1
    $exit = $LASTEXITCODE
    if ($exit -ne 0) { throw "fontconvert exit=$exit (Regular $px). Output: `n$out" }
    $out | Set-Content -Encoding ASCII -Path $regOut
    Write-Host "OK Regular $px -> $regOut"
  } catch {
    Write-Error ("FAILED Regular {0}: {1}" -f $px, $_)
  }

  # Bold
  try {
    $out = & $FontconvertExe $BoldTTF $px $cpFirst $cpLast 2>&1
    $exit = $LASTEXITCODE
    if ($exit -ne 0) { throw "fontconvert exit=$exit (Bold $px). Output: `n$out" }
    $out | Set-Content -Encoding ASCII -Path $bdOut
    Write-Host "OK Bold    $px -> $bdOut"
  } catch {
    Write-Error ("FAILED Bold {0}: {1}" -f $px, $_)
  }
}

# Parse generated headers to extract GFXfont symbol names
function Get-FontSymbol($file) {
  $text = Get-Content -Raw -Path $file
  # Look for line: const GFXfont <name> PROGMEM = { ... } or without PROGMEM
  $m = [regex]::Match($text, "const\s+GFXfont\s+([A-Za-z0-9_]+)")
  if ($m.Success) { return $m.Groups[1].Value }
  throw "Unable to find GFXfont symbol in $file"
}

$regMap = @{}
$bdMap  = @{}
foreach ($px in $pxList) {
  $regFile = Join-Path $regDir ("tnr_ru_{0}pt7b.h" -f $px)
  $bdFile  = Join-Path $bdDir  ("tnr_rubd_{0}pt7b.h" -f $px)
  $regMap[$px] = @{ file = (Resolve-Path $regFile).Path; sym = (Get-FontSymbol $regFile) }
  $bdMap[$px]  = @{ file = (Resolve-Path $bdFile).Path;  sym = (Get-FontSymbol $bdFile) }
}

# Compose TimesAllRU.h
$hdrPath = Join-Path $rusRoot 'TimesAllRU.h'
$sb = New-Object System.Text.StringBuilder
$null = $sb.AppendLine('#pragma once')
$null = $sb.AppendLine('#include <ST77xxDMA.h>')
$null = $sb.AppendLine('')
$null = $sb.AppendLine('// Auto-generated aggregator: Times New Roman (RU) Regular/Bold, range U+0400..U+045F')
$null = $sb.AppendLine('// Generated by tools/fonts/gen_times_ru_gfxff.ps1')
$null = $sb.AppendLine('')

# Includes
foreach ($px in $pxList) {
  $incReg = (Resolve-Path $regMap[$px].file).Path.Replace($repoRoot + '\\', '')
  $incBd  = (Resolve-Path $bdMap[$px].file).Path.Replace($repoRoot + '\\', '')
  $incReg = $incReg -replace '\\','/'
  $incBd  = $incBd -replace '\\','/'
  $null = $sb.AppendLine("#include <${incReg}>")
  $null = $sb.AppendLine("#include <${incBd}>")
}
$null = $sb.AppendLine('')
$null = $sb.AppendLine('namespace TimesRUFF {')
$null = $sb.AppendLine('  inline uint8_t clampPx(uint8_t px) { if (px < 5) return 5; if (px > 40) return 40; return px; }')
$null = $sb.AppendLine('  inline const GFXfont* regular(uint8_t px) {')
$null = $sb.AppendLine('    switch (clampPx(px)) {')
foreach ($px in $pxList) {
  $sym = $regMap[$px].sym
  $null = $sb.AppendLine(("      case {0}: return &{1};" -f $px, $sym))
}
$null = $sb.AppendLine('      default: return nullptr;')
$null = $sb.AppendLine('    }')
$null = $sb.AppendLine('  }')
$null = $sb.AppendLine('  inline const GFXfont* bold(uint8_t px) {')
$null = $sb.AppendLine('    switch (clampPx(px)) {')
foreach ($px in $pxList) {
  $sym = $bdMap[$px].sym
  $null = $sb.AppendLine(("      case {0}: return &{1};" -f $px, $sym))
}
$null = $sb.AppendLine('      default: return nullptr;')
$null = $sb.AppendLine('    }')
$null = $sb.AppendLine('  }')
$null = $sb.AppendLine('}')

$sb.ToString() | Set-Content -Encoding ASCII -Path $hdrPath
Write-Host "Wrote aggregator: $hdrPath"

Write-Host "Done. NOTE: U+2116 (No sign) is not in block 0x0400..0x045F and is not included. If needed, add separately later (extra font/fallback)."
